# Generated by Django 2.1.7 on 2025-02-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyberSecurityApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
